apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-admin
    receivers:
      - uid: email-admin-receiver
        type: email
        settings:
          addresses: enrique.rami.lopez@gmail.com
          singleEmail: true
